export const CREATE_TRANSACTION = 'TRANSACTION/CREATE_TRANSACTION';
export const FETCH_TRANSACTION = 'TRANSACTION/FETCH_TRANSACTION';
export const REMOVE_TRANSACTION = 'TRANSACTION/REMOVE_TRANSACTION';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';